//SELECT * FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_jyotsana_porwal;

Create Or replace table INTERVIEW_DB.PLAYGROUND_JYOTSANA_PORWAL.covid_cases_fresh_data_dim_tab
(
GROWTH_FACTOR_OF_NEW_DEATHS float,
NEW_CASES_PER_MILLION float,
NEW_DEATHS_PER_MILLION float,
NEW_RECOVERED number(38,0),
NEW_DEATHS number(38,0),
NEW_CASES number(38,0),
DATE varchar(256),
NEW_ACTIVE_CASES number(38,0),
COUNTRY varchar(256),
TOTAL_DEATHS_PER_MILLION float,
GROWTH_FACTOR_OF_NEW_CASES float,
_ROW number(38,0)
)

INSERT INTO INTERVIEW_DB.PLAYGROUND_JYOTSANA_PORWAL.covid_cases_fresh_data_dim_tab (
GROWTH_FACTOR_OF_NEW_DEATHS,
NEW_CASES_PER_MILLION,
NEW_DEATHS_PER_MILLION,
NEW_RECOVERED,
NEW_DEATHS,
NEW_CASES,
DATE,
NEW_ACTIVE_CASES,
COUNTRY,
TOTAL_DEATHS_PER_MILLION,
GROWTH_FACTOR_OF_NEW_CASES,
_ROW
)
SELECT GROWTH_FACTOR_OF_NEW_DEATHS,
NEW_CASES_PER_MILLION,
NEW_DEATHS_PER_MILLION,
NEW_RECOVERED,
NEW_DEATHS,
NEW_CASES,
DATE,
NEW_ACTIVE_CASES,
COUNTRY,
TOTAL_DEATHS_PER_MILLION,
GROWTH_FACTOR_OF_NEW_CASES,
_ROW
 FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_jyotsana_porwal
 
 //SELECT * FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_jyotsana_porwal;
Create Or replace table INTERVIEW_DB.PLAYGROUND_JYOTSANA_PORWAL.covid_cases_Geography_wise_data_dim_tab
(
TOTAL_CITIES NUMBER(38,0),
TOTAL_DISTRICTS NUMBER(38,0),
ISLAND VARCHAR(256),
LONGITUDE float,
PROVINCE VARCHAR(256),
TOTAL_URBAN_VILLAGES number(38,0),
LOCATION_LEVEL VARCHAR(256),
AREA_KM_2_ number(38,0),
TIME_ZONE VARCHAR(256),
TOTAL_RURAL_VILLAGES number(38,0),
LATITUDE FLOAT,
LOCATION_ISO_CODE VARCHAR(256),
TOTAL_REGENCIES number(38,0),
POPULATION_DENSITY FLOAT,
POPULATION number(38,0),
_ROW number(38,0)
)



INSERT INTO INTERVIEW_DB.PLAYGROUND_JYOTSANA_PORWAL.covid_cases_Geography_wise_data_dim_tab (
TOTAL_CITIES,
TOTAL_DISTRICTS,
ISLAND,
LONGITUDE,
PROVINCE,
TOTAL_URBAN_VILLAGES,
LOCATION_LEVEL,
AREA_KM_2_,
TIME_ZONE,
TOTAL_RURAL_VILLAGES,
LATITUDE,
LOCATION_ISO_CODE,
TOTAL_REGENCIES,
POPULATION_DENSITY,
POPULATION,
_ROW
)
SELECT TOTAL_CITIES,
TOTAL_DISTRICTS,
ISLAND,
LONGITUDE,
PROVINCE,
TOTAL_URBAN_VILLAGES,
LOCATION_LEVEL,
AREA_KM_2_,
TIME_ZONE,
TOTAL_RURAL_VILLAGES,
LATITUDE,
LOCATION_ISO_CODE,
TOTAL_REGENCIES,
POPULATION_DENSITY,
POPULATION,
_ROW
 FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_jyotsana_porwal

//Similarly creating one more table on total covid cases present 
 

//Regions with highest death rates etc.
Select (TOTAL_DEATHS/POPULATION)*100000 as death_rate,Country, Province, CONTINENT
from 
FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_jyotsana_porwal
group by TOTAL_DEATHS, POPULATION, COUNTRY, PROVINCE, CONTINENT order by death_rate DESC
